const myFoo = async (req,res)=>{
    try {
        
    } catch (error) {
        
    }
}